spring.application.name=backend
spring.jackson.property-naming-strategy=SNAKE_CASE
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update